### ISSUE TITLE
v0.0.3, p 43 grid layout

### ISSUE THREAD

**Issue by ingwinlu** [BuildItWithNitrogen/builditwithnitrogen#19]
since the grid layout has been moved to the template:

```
<body>
    <div class=container_12>
        <div class="grid_8 prefix_2 suffix_2">
            <div class="grid">
                <a href="/">
                    <img src="/images/logo.png" style="width:600px" />
                </a>
                [[[page:body()]]]
            </div>
        </div>
    </div>
    <script>
    [[[script]]]
    </script>
</body>
```

it should be removed from body() in index.erl as well, else the text gets an unwanted offset:
![offset](https://cloud.githubusercontent.com/assets/4435962/4391570/6797a260-4406-11e4-86e3-8fcd08a7cbcf.PNG)

wrong snipped:

```
inner_body() ->
   [ 
      #h1 { text="WELCOME!" },
      #h2 { text="Joe Armstrong" },
      #h2 { text="Rusty Klopaus" }
   ].
```

solution would be to just remove `inner_body` completely and change the code snipped to:

```
body() ->
   [ 
      #h1 { text="WELCOME!" },
      #h2 { text="Joe Armstrong" },
      #h2 { text="Rusty Klopaus" }
   ].
```

later, when adding the query for inserted visitors p.64, the `inner_body` is already removed and the content is in `body`, so there is no need to change that

**Comment by choptastic** [comment]
Thanks. You're completely right there.
