### ISSUE TITLE
Syntax error in Dets code example

### ISSUE THREAD

**Issue by alexpopov** [BuildItWithNitrogen/builditwithnitrogen#23]
Page 52: Projects > nitroboard I > 3.11 visitors 
The example has: 
`23> CC. = V4#visitor.company.`
but the period after the CC will obviously end the code there and causes a `syntax error before '='`

Right after that:
`25> Formatted_Visitors = [format_visitor(Visitor) || Visitor <- Visitors]`
seems to be missing a period at the end, also I get `Visitors unbound`. I don't think I missed anything. Dets closed the visitors database, but that was lowercase anyway.

One final thing for tonight: bottom of page 53
`~/nb/site/src$ vim visitors_db:erl` 
I don't think you meant to put that colon there, instead of `.erl`
EDIT: same issue appears with `~/nb/site/src$ vim visitors_admin:erl`, now I'm concerned that I missed some vital part of Erlang's naming scheme. 

Loving the book, @alexpopovjr :)

**Comment by choptastic** [comment]
Thanks, Fixed. New version coming out later today or this weekend.
