### ISSUE TITLE
Various Places in Code with improper quotes used.

### ISSUE THREAD

**Issue by alexpopov** [BuildItWithNitrogen/builditwithnitrogen#24]
For example, Page 72, in the code block for `get_associates\0` there are curly quotes used which makes copy-pasting pretty difficult. I caught this earlier as well as here: 
`List = lists:sort(dets:match_object(associates, ’_’))`

**Comment by choptastic** [comment]
We're going to be find-replacing these improper quotes in bulk. It's quite the nuisance in the editor.
