### ISSUE TITLE
v.0.0.4, p. 183, word repeated

### ISSUE THREAD

**Issue by pel-daniel** [BuildItWithNitrogen/builditwithnitrogen#25]
The word **can** is repeated in the following paragraph:

Now anyone on the web **can can** “grok” your prototype simply by entering
http://<assigned hexidecimal>.ngrok.com in their browser .

**Comment by choptastic** [comment]
Also fixed. Thanks again!

**Comment by choptastic** [comment]
A new version should be ready relatively soon.
