### ISSUE TITLE
v 0.0.4, p. 219, typo

### ISSUE THREAD

**Issue by pel-daniel** [BuildItWithNitrogen/builditwithnitrogen#26]
O'R**ie**lly -> O'R**ei**lly
Gentle introduction: St. Laurent, Simon, Introducing Erlang, **O’Rielly**,
2013

**Comment by choptastic** [comment]
Thanks so much for the reports - keep em coming! We should have a new version with new chapters out soon!

**Comment by choptastic** [comment]
Fixed in the WIP. Thanks again.
