### ISSUE TITLE
visitors_db:erl

### ISSUE THREAD

**Issue by ghost** [BuildItWithNitrogen/builditwithnitrogen#29]
On page 53 in the v0.1.0 PDF (nitroboard I section) 

the text states to create "visitors_db.erl" in the code example box it is 

$ vim visitors_db:erl

**Comment by choptastic** [comment]
Thank you!

On Wed, Jul 15, 2015 at 5:18 PM, goldfisch notifications@github.com wrote:

> On page 53 in the v0.1.0 PDF (nitroboard I section)
> 
> the text states to create "visitors_db.erl" in the code example box it is
> 
> $ vim visitors_db:erl
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/choptastic/builditwithnitrogen/issues/29.

## 

Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
