### ISSUE TITLE
v0.0.3, p48, output of record input seems bugged

### ISSUE THREAD

**Issue by ingwinlu** [BuildItWithNitrogen/builditwithnitrogen#3]
```
#visitor{date = {2014,5,30},
time = {11,25,54},
name = "Jesse James",
company = "Erlingo!"} Time
```

the Time is too much, formatting of both code blocks on the page seems off somehow though

**Comment by choptastic** [comment]
Thanks. That whole bit seemed a little wonky and rushed. Fixed to not seem so terrible.
