### ISSUE TITLE
NB1: put_vip/2

### ISSUE THREAD

**Issue by ghost** [BuildItWithNitrogen/builditwithnitrogen#31]
in version 0.1.0 on page 54 the put_vip/2 function does not look completed for me in the source example (maybe i did miss somethin) but from my point of view compared with the put_visitor/1 it is missing the put_visitor/1 call to push the vip to the DB where Record is the VIP coming in today

**Comment by choptastic** [comment]
You definitely did not miss anything. Thanks. It'll be fixed in the next
release.

-Jesse

On Wed, Jul 15, 2015 at 5:52 PM, goldfisch notifications@github.com wrote:

> in version 0.1.0 on page 54 the put_vip/2 function does not look completed
> for me in the source example (maybe i did miss somethin) but from my point
> of view compared with the put_visitor/1 it is missing the
> open_visitors_db/0 and close_visitors/0 calls + the insert
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/choptastic/builditwithnitrogen/issues/31.

## 

Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
