### ISSUE TITLE
v0.0.3, p 42, image link

### ISSUE THREAD

**Issue by ingwinlu** [BuildItWithNitrogen/builditwithnitrogen#6]
image link needs to be absolute so the logo also gets displayed when building the admin page(p58+) later.

`<img src="../images/logo.png" style="width:600px" />` to `<img src="/images/logo.png" style="width:600px" />`

**Comment by choptastic** [comment]
Thanks. Fixed interally.

**Comment by ingwinlu** [comment]
the img should probably also be width: 100% instead of the px value
