### ISSUE TITLE
v0.0.3, p 59, postback too much or missing event

### ISSUE THREAD

**Issue by ingwinlu** [BuildItWithNitrogen/builditwithnitrogen#8]
the done button sends an event which is not caught by event later, while it is technically no biggy, it might confuse learners. 

either remove the postback or add event(s) which cover it.
i went for something like this, since for me it made sense to confirm the done button as well (since partly entered information might go missing, we don't know if  ~~the bossmonster~~ ms Moneypenny might be a bit clumsy), also showoff wf:redirect("/")

```
        #label {text="Company"},
        #textbox{ id=company},
        #br{},
        #button{postback=done, text="Done"},
        #button{id=save, postback=save, text="Save"}
    ].

event(done) ->
    wf:wire(#confirm{text="Done?", postback=done_ok});
event(done_ok) ->
    wf:redirect("/");
event(save) ->
    wf:wire(#confirm{text="Save?", postback=save_ok});
event(save_ok) ->
    Time = wf:depickle(wf:q(time)),
    Name = wf:q(name),
    Company = wf:q(company),
    Date = parse_date(wf:q(date1)),
    Record = #visitor{date=Date, time=Time, name=Name,
        company=Company}, visitors_db:put_visitor(Record),
    wf:wire(#clear_validation{}),
    wf:update(inner_body, inner_body()).
```

**Comment by choptastic** [comment]
That's a good find. The whole "Redirect without a popup" could, like you said, lead to loss of form info.  I'll make the suggested adjustments, and do a little code cleanup on this in general.
